### PR TITLE
Implement support for provider root CA configuration

### PR DESCRIPTION
**Pull request by rickardgranberg**
This is a suggested implementation to fix issue #23

### CODE REVIEW

**Comment by rickardgranberg** [comment]
Not sure I understand why the build failed... 
Tried running staticcheck on my machine and I don't see that error. 
And I haven't added/changed any dependencies either

**Comment by ripienaar** [comment]
hmm, if you go `go mod tidy` no changes?

**Comment by rickardgranberg** [comment]
> hmm, if you go `go mod tidy` no changes?

No, does nothing. I even tried `go mod tidy -compat=1.16` in case there was something caused by me having Go 1.17 installed, but still nothing.

**Comment by rickardgranberg** [comment]
OK, it was caused by me using Go 1.17. I spun up a dev container in VS Code with Go 1.16 and was able to reproduce the issue.

**Comment by ripienaar** [comment]
Ah yes, that'll do it.

OK I will take a look at this next week, this week got a bit crazy, thanks a lot

**Comment by ripienaar** [comment]
This is great thanks, I'll look to add other connection options like user/pass/token etc as well, might then also support cert and key as tls options.

**Pull request merged**
